[package]
name = "rinput"
version = "0.1.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2018"

[dependencies]
uinput = "0.1.3"
lazy_static = "1.4.0"
users = "0.10.0"
structopt = "0.3.15"
hostname = "0.3.1"